### ISSUE TITLE
Custom Domain Email

### ISSUE THREAD

**Issue by KendallDoesCoding** [emmalearnscode/portfolio#3]
To make your email look more professional, I suggest you make a email like emma@emmadawson.dev and update it on your site as well as on README.MD of your profile. I can give you some tools, etc to do this for absolutely free if your down. As mentioned above, according to me this looks little more professional :)

**Comment by EmmaDawsonDev** [comment]
Thanks, right now I'm not interested as my current email works pretty well for my needs.

**Comment by KendallDoesCoding** [comment]
> Thanks, right now I'm not interested as my current email works pretty well for my needs.

Ok cool.
